services:
  postgres:
    image: postgres:17
    container_name: blog_postgres
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"